routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Route;

Route::get('/', 'HomeController@index')->name('home');

// Localization
Route::get('/js/lang.js', function () {
    $strings = Cache::rememberForever('lang.js', function () {
        $lang = config('app.locale');

        $files   = glob(resource_path('lang/' . $lang . '/*.php'));
        $strings = [];

        foreach ($files as $file) {
            $name           = basename($file, '.php');
            $strings[$name] = require $file;
        }

        return $strings;
    });

    header('Content-Type: text/javascript');
    echo('window.i18n = ' . json_encode($strings) . ';');
    exit();
})->name('assets.lang');

Auth::routes();

Route::name('board.')->group(function() {
    Route::prefix('board')->group(function() {
        Route::get('/{itemType?}', 'BoardController@index')->name('index')->middleware('auth');

        Route::get('test', 'BoardController@test')->name('test');
    });
});

Route::name('item.')->group(function() {
   Route::prefix('item')->group(function() {
       Route::get('/view/{item}', 'ItemController@view')->name('view')->middleware('auth');
       Route::get('/edit/{item}', 'ItemController@edit')->name('edit')->middleware('auth');
       Route::post('/save/{item?}', 'ItemController@save')->name('save')->middleware('auth');
       Route::get('/new/{itemType}', 'ItemController@newItem')->name('new')->middleware('auth');
       Route::get('/delete/{item}', 'ItemController@delete')->name('delete')->middleware('auth');
   });
});

Route::name('user.')->group(function() {
    Route::prefix('user')->group(function() {
        Route::get('/settings', 'UserController@settings')
            ->name('settings')->middleware('auth');
        Route::post('/settings/password', 'UserController@password')
            ->name('settings.password')->middleware('auth');
        Route::post('/settings/{property}','UserController@changeProperty')
            ->name('settings.property')->middleware('auth');
    });
});

Route::name('data.')->group(function() {
    Route::prefix('data')->group(function() {
        Route::get('/itemtype', 'DataSourceController@getItemTypes')->name('itemtype')->middleware('auth');
    });
});

resources/views/views/board.blade.php
@extends('layouts.main')

@section('content')
    <items-container items-src="{{ $items }}"></items-container>
@endsection

resources/views/views/home.blade.php
@extends('layouts.main')

@section('content')
<div class="box content-container has-text-justified">
    {{ __('app.home_page_description') }}
</div>
@endsection

resources/views/views/item-note.blade.php
@extends('layouts.main')

@section('content')
<div class="box content-container">
    <form action="{{ route('item.save') }}" method="POST">
        @csrf

        <input type="hidden" name="id" value="{{ $item->id }}" />
        <input type="hidden" name="item_type_id" value="{{ $item->item_type_id }}" />

        <div class="columns">
            <div class="column">
                <div class="field">
                    <label for="item-name" class="label">{{ __('app.Name') }}:</label>
                    <div class="control">
                        <input id="item-name"
                               type="text"
                               class="input @if(!$isEditable) is-static @endif"
                               name="name"
                               value="{{ $item->name }}" />
                    </div>
                </div>
            </div>

            <div class="column">
                <div class="field">
                    <label for="item-folder" class="label">{{ __('app.Folder') }}:</label>
                    <div class="control">
                        <input type="text"
                               id="item-folder"
                               class="input @if(!$isEditable) is-static @endif"
                               name="folder"
                               value="{{ $item->folder }}">
                    </div>
                </div>
            </div>
        </div>

        <div class="columns">
            <div class="column">
                <label for="item-comments" class="label">{{ __('app.Note') }}:</label>
                <textarea name="comments"
                          id="item-comments"
                          rows="5"
                          @if(!$isEditable) disabled @endif
                          class="textarea has-fixed-size">{{ $item->comments }}</textarea>
            </div>
        </div>

        <div class="has-text-right">
            <a href="{{ $prev_url }}" class="button is-primary">{{ __('app.Cancel') }}</a>
            @if(!$isEditable)
                <a href="{{ route('item.edit', $item->id) }}" class="button is-info">{{ __('app.Edit') }}</a>
            @else
                <button type="submit" class="button is-info">{{ __('app.Save') }}</button>
            @endif
        </div>
    </form>

</div>
@endsection

resources/views/views/item.blade.php
@extends('layouts.main')

@section('content')
<div class="box content-container">
    @if (session('err'))
        <?php var_dump(session('err')); ?>
        @if (is_array(session('err')))
            @foreach(session('err')->all() as $error)
                <div class="errors-item-form">
                    <p class="has-text-danger">{{ $error }}</p>
                </div>
            @endforeach
        @else
            <div class="errors-item-form">
                <p class="has-text-danger">{{ $err ?? '' }}</p>
            </div>
        @endif
    @endif

    <form action="{{ route('item.save') }}" method="POST">
        @csrf

        <input type="hidden" name="id" value="{{ $item->id }}" />
        <input type="hidden" name="item_type_id" value="{{ $item->item_type_id }}" />

        <div class="field">
            <label for="item-name" class="label">{{ __('app.Name') }}:</label>
            <div class="control">
                <input id="item-name"
                       type="text"
                       class="input @if(!$isEditable) is-static @endif"
                       name="name"
                       value="{{ $item->name }}" />
            </div>
        </div>

        <div class="columns">
            <div class="column">
                <div class="field">
                    <label for="item-url" class="label">{{ __('app.URL') }}:</label>
                    <div class="control">
                        <input type="text"
                               id="item-url"
                               class="input @if(!$isEditable) is-static @endif"
                               name="url"
                               value="{{ $item->url }}">
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="field">
                    <label for="item-folder" class="label">{{ __('app.Folder') }}:</label>
                    <div class="control">
                        <input type="text"
                               id="item-folder"
                               class="input @if(!$isEditable) is-static @endif"
                               name="folder"
                               value="{{ $item->folder }}">
                    </div>
                </div>
            </div>
        </div>

        <div class="columns">
            <div class="column">
                <div class="field">
                    <label for="item-username" class="label">{{ __('app.Username') }}:</label>
                    <div class="control">
                        <input type="text"
                               id="item-username"
                               class="input @if(!$isEditable) is-static @endif"
                               name="username"
                               value="{{ $item->username }}">
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="field">
                    <label for="item-password" class="label">{{ __('app.Password') }}:</label>
                    <div class="control">
                        <input type="text"
                               id="item-password"
                               class="input @if(!$isEditable) is-static @endif"
                               name="password"
                               value="{{ $item->password }}">
                    </div>
                </div>
            </div>
        </div>

        <div class="columns">
            <div class="column">
                <label for="item-comments" class="label">{{ __('app.Comments') }}:</label>
                <textarea name="comments"
                          id="item-comments"
                          rows="5"
                          @if(!$isEditable) disabled @endif
                          class="textarea has-fixed-size">{{ $item->comments }}</textarea>
            </div>
        </div>

        <div class="has-text-right">
            <a href="{{ $prev_url }}" class="button is-primary">{{ __('app.Cancel') }}</a>
            @if(!$isEditable)
                <a href="{{ route('item.edit', $item->id) }}" class="button is-info">{{ __('app.Edit') }}</a>
            @else
                <button type="submit" class="button is-info">{{ __('app.Save') }}</button>
            @endif
        </div>
    </form>

</div>
@endsection

resources/views/views/left_menu.blade.php
<aside class="menu left-menu-container left-content-column">
    <p class="menu-label">
        Security Items
    </p>

    <ul class="menu-list">
        <li>
            <a href="{{ route('board.index') }}"
               class="@if (($activeMenu ?? '') === '') has-background-light @endif">{{ __('app.All Items') }}</a>
        </li>
        <li>
            <a href="{{ route('board.index', ['itemType' => 'password']) }}"
               class="@if (($activeMenu ?? '') === 'password') has-background-light @endif">{{ __('app.Passwords') }}</a>
        </li>
        <li>
            <a href="{{ route('board.index', ['itemType' => 'note']) }}"
               class="@if (($activeMenu ?? '') === 'note') has-background-light @endif">{{ __('app.Notes') }}</a>
        </li>
        <li>
            <a href="{{ route('user.settings') }}"
               class="@if (($activeMenu ?? '') === 'user.settings') has-background-light @endif">{{ __('app.Settings') }}</a>
        </li>
    </ul>
</aside>

resources/views/views/top_content.blade.php
@auth()
<form action="{{ route('board.index') }}">
    <div class="columns">
        <div class="column is-8">
            <div class="field is-fullwidth">
                <div class="control has-icons-left">
                    <input type="text" class="input" name="search" />
                    <span class="icon is-small is-left">
                        <i class="fas fa-search"></i>
                    </span>
                </div>
            </div>
        </div>

        <div class="column is-2">
            <div class="field">
                <button type="submit" class="button is-primary is-fullwidth">{{ __('app.Search') }}</button>
            </div>
        </div>

        <div class="column is-2">
            <select-new-item></select-new-item>
        </div>
    </div>
</form>
@endauth

resources/views/views/user-settings.blade.php
@extends('layouts.main')

@section('content')
    <settings-container user="{{$user}}"></settings-container>
@endsection